---
# tasks file for uakami.webserver

- name: apt official nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key

- name: apt official nginx repository
  apt_repository: repo="deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"

- name: install nginx
  apt: >
    name=nginx
    state=latest
    force=yes
    update_cache=yes
    cache_valid_time=3600

- name: remove default sites conf from nginx
  file: path={{ item }} state=absent
  with_items:
    - "/etc/nginx/conf.d/default.conf"
    - "/etc/nginx/conf.d/example_ssl.conf"
    - "/etc/nginx/sites-enabled/"
    - "/etc/nginx/sites-available/"
  notify:
    - reload nginx
