# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ufvalue',
            options={'verbose_name': 'uf value', 'verbose_name_plural': 'uf values'},
        ),
        migrations.AlterUniqueTogether(
            name='ufvalue',
            unique_together=set([('value', 'date')]),
        ),
    ]
