# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uf_app', '0003_auto_20171126_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufvalue',
            name='date',
            field=models.DateField(unique=True, verbose_name='Value date'),
        ),
        migrations.AlterUniqueTogether(
            name='ufvalue',
            unique_together=set([]),
        ),
    ]
